import { createEventBus, createGameState, getInventoryAmount, getResourceQuantity, getSkill } from './core.js';
import { BIOMES, BIOME_ASSIGNMENTS, CONFIG, ITEMS, RECIPES, RESOURCE_NODES, RESOURCE_NODES_BY_POSITION, SKILLS, SKILL_NODES } from './content.js';
import { createBiomeRegistry } from './biomes.js';
import { createRules } from './systems.js';
import { createCraftingRules } from './crafting.js';
import { clearSave, readSave, saveGame, applyLoadedState } from './persistence.js';

const elements = { grid: document.querySelector('#grid'), inspector: document.querySelector('#state-inspector'), consoleOutput: document.querySelector('#console-output'), consoleForm: document.querySelector('#console-form'), consoleInput: document.querySelector('#console-input'), resetButton: document.querySelector('#reset-button'), statusBadge: document.querySelector('#status-badge') };
const eventBus = createEventBus();
const state = createGameState(CONFIG.startPosition, RESOURCE_NODES, SKILLS);
state.worldTime ??= 0; state.resourceRespawns ??= {};
const biomes = createBiomeRegistry(BIOMES, BIOME_ASSIGNMENTS);
const rules = createRules({ config: CONFIG, resourceNodesByPosition: RESOURCE_NODES_BY_POSITION, eventBus, skills: SKILLS, skillNodes: SKILL_NODES, biomeRegistry: biomes });
const crafting = createCraftingRules({ recipes: RECIPES, eventBus });
const write = (message, type = 'system') => { if (!elements.consoleOutput) return; const line = document.createElement('div'); line.className = `console-line ${type}`; line.textContent = message; elements.consoleOutput.append(line); elements.consoleOutput.scrollTop = elements.consoleOutput.scrollHeight; };
const setStatus = message => { if (elements.statusBadge) elements.statusBadge.textContent = message; };
function advanceTime(amount = 1) { state.worldTime += amount; const respawned = []; for (const node of Object.values(RESOURCE_NODES)) { const at = state.resourceRespawns[node.id]; if (at !== undefined && state.worldTime >= at) { state.resources[node.id] = node.maxQuantity; delete state.resourceRespawns[node.id]; respawned.push(node.id); } } return respawned; }
function render() { if (!elements.grid || !elements.inspector) return; elements.grid.replaceChildren(); for (let y = 0; y < CONFIG.gridHeight; y++) for (let x = 0; x < CONFIG.gridWidth; x++) { const cell = document.createElement('div'); const node = RESOURCE_NODES_BY_POSITION.get(`${x},${y}`); cell.className = `cell ${biomes.getBiomeAt(x, y).visualClass}`; cell.setAttribute('aria-label', `Cell ${x}, ${y}`); if (rules.isBlocked(x, y)) cell.classList.add('blocked'); if (node && getResourceQuantity(state, node.id) > 0) { cell.classList.add('resource'); cell.title = `${node.name} (${getResourceQuantity(state, node.id)} remaining)`; } if (state.player.x === x && state.player.y === y) cell.classList.add('player'); elements.grid.append(cell); } elements.grid.style.gridTemplateColumns = `repeat(${CONFIG.gridWidth}, 1fr)`; elements.grid.style.gridTemplateRows = `repeat(${CONFIG.gridHeight}, 1fr)`; const skill = getSkill(state, 'foraging'); const biome = biomes.getBiomeAt(state.player.x, state.player.y); const remaining = Object.values(RESOURCE_NODES).reduce((n, node) => n + getResourceQuantity(state, node.id), 0); const maximum = Object.values(RESOURCE_NODES).reduce((n, node) => n + node.maxQuantity, 0); elements.inspector.innerHTML = `<dt>Position</dt><dd>${state.player.x}, ${state.player.y}</dd><dt>Biome</dt><dd>${biome.name}</dd><dt>World time</dt><dd>${state.worldTime}</dd><dt>Inventory</dt><dd>${Object.entries(state.inventory).filter(([, n]) => n > 0).map(([id, n]) => `${ITEMS[id]?.name ?? id}: ${n}`).join(', ') || 'Empty'}</dd><dt>Foraging</dt><dd>Level ${skill.level}; ${skill.xp} XP</dd><dt>Resources</dt><dd>${remaining}/${maximum}</dd><dt>Respawn timers</dt><dd>${Object.keys(state.resourceRespawns).length}</dd>`; }
function show(result) { setStatus(result.success ? (result.code ?? 'Ready') : 'Failed'); write(`${result.code ?? (result.success ? 'OK' : 'ERROR')}: ${result.message}`, result.success ? 'system' : 'error'); render(); }
function snapshot() { return JSON.parse(JSON.stringify({ player: state.player, inventory: state.inventory, skills: state.skills, capabilities: state.capabilities, resources: state.resources, resourceRespawns: state.resourceRespawns, worldTime: state.worldTime, stats: state.stats, actionLog: state.actionLog, lastAction: state.lastAction })); }
function runTests() { const before = snapshot(); const tests = []; const assert = (name, condition) => tests.push({ name, passed: Boolean(condition) }); try { assert('Biome registry is valid', biomes.validateResourceNodes(RESOURCE_NODES).valid); assert('Resource biome placements are valid', biomes.validateResourceNodes(RESOURCE_NODES).valid); assert('Default cell has a biome', biomes.getBiomeAt(0, 0).id === 'meadow'); assert('Forest cell resolves correctly', biomes.getBiomeAt(10, 7).id === 'forest'); state.player = { x: 2, y: 1 }; assert('Meadow gathering works', rules.gather(state).success); } finally { applyLoadedState(state, before); } const passed = tests.filter(t => t.passed).length; write(`${passed}/${tests.length} tests passed.\n${tests.map(t => `${t.passed ? 'PASS' : 'FAIL'} ${t.name}`).join('\n')}`, passed === tests.length ? 'system' : 'error'); render(); return { passed: passed === tests.length, tests }; }
function inspectCell(x, y) { if (!Number.isInteger(x) || !Number.isInteger(y) || x < 0 || y < 0 || x >= CONFIG.gridWidth || y >= CONFIG.gridHeight) return write('ERROR: Usage: inspectcell <x> <y>', 'error'); write(JSON.stringify({ x, y, biome: biomes.getBiomeAt(x, y), resource: RESOURCE_NODES_BY_POSITION.get(`${x},${y}`) ?? null }, null, 2)); }
function executeCommand(raw) { const input = raw.trim(); if (!input) return; const [command, ...args] = input.toLowerCase().split(/\s+/); if (command === 'help') write('Commands: help, state, actions, recipes, biome, inspectcell x y, validatebiomes, save, load, clearsave, craft recipeId, teleport x y, gather, refill, time, advance n, respawns, tests, reset, clear.'); else if (command === 'state') write(JSON.stringify(state, null, 2)); else if (command === 'actions') write(JSON.stringify(state.actionLog, null, 2)); else if (command === 'recipes') write(Object.values(RECIPES).map(r => `${r.id}: ${Object.entries(r.inputs).map(([id, n]) => `${n} ${ITEMS[id]?.name ?? id}`).join(', ')} -> ${r.output.amount} ${ITEMS[r.output.itemId]?.name ?? r.output.itemId}`).join('\n\n')); else if (command === 'biome') write(JSON.stringify(biomes.getBiomeAt(state.player.x, state.player.y), null, 2)); else if (command === 'inspectcell') inspectCell(Number(args[0]), Number(args[1])); else if (command === 'validatebiomes') { const r = biomes.validateResourceNodes(RESOURCE_NODES); write(r.valid ? 'BIOMESVALID: All resource biome placements are valid.' : `BIOMESINVALID: ${r.errors.join(' ')}`, r.valid ? 'system' : 'error'); } else if (command === 'tests') runTests(); else if (command === 'gather') show(rules.gather(state)); else if (command === 'craft') show(crafting.craft(state, args[0])); else if (command === 'refill') show(rules.refillResources(state, RESOURCE_NODES)); else if (command === 'teleport') show(rules.teleport(state, Number(args[0]), Number(args[1]))); else if (command === 'time') { write(`TIME: World time ${state.worldTime}.`); render(); } else if (command === 'advance') { const n = Number(args[0]); if (!Number.isInteger(n) || n < 1) write('ERROR: Usage: advance <positive integer>.', 'error'); else { const respawned = advanceTime(n); write(`TIME: Advanced ${n}; respawned: ${respawned.join(', ') || 'none'}.`); render(); } } else if (command === 'respawns') { const timers = Object.values(RESOURCE_NODES).filter(n => state.resourceRespawns[n.id] !== undefined).map(n => `${n.name}: ${state.resourceRespawns[n.id] - state.worldTime} remaining`); write(timers.join('\n') || 'No active respawn timers.'); render(); } else if (command === 'save') { const payload = saveGame(state); write(`SAVED: Game saved at ${payload.savedAt}.`); } else if (command === 'load') { const r = readSave(); if (r.success) { applyLoadedState(state, r.state); write(`LOADED: Save from ${r.savedAt}.`); render(); } else write(`${r.code}: ${r.message}`, 'error'); } else if (command === 'clearsave') { clearSave(); write('SAVECLEARED: Local save deleted.'); } else if (command === 'clear') elements.consoleOutput.replaceChildren(); else if (command === 'reset') { clearSave(); location.reload(); } else write(`Unknown command: ${command}. Type help.`, 'error'); }
const directions = { ArrowUp: [0, -1], w: [0, -1], ArrowDown: [0, 1], s: [0, 1], ArrowLeft: [-1, 0], a: [-1, 0], ArrowRight: [1, 0], d: [1, 0] }; elements.grid?.addEventListener('keydown', event => { const d = directions[event.key]; if (d && event.target !== elements.consoleInput) { event.preventDefault(); move(...d); } }); elements.grid?.addEventListener('click', () => elements.grid.focus()); elements.resetButton?.addEventListener('click', () => { clearSave(); location.reload(); }); elements.consoleForm?.addEventListener('submit', event => { event.preventDefault(); executeCommand(elements.consoleInput.value); elements.consoleInput.value = ''; elements.consoleInput.focus(); });
function move(dx, dy) { show(rules.move(state, dx, dy)); }
render(); write('Foundation loaded. Type help for commands.'); runTests(); window.gridRpg = { state, rules, crafting, executeCommand, render, runTests };
